### ISSUE TITLE
working wiht NAS

### ISSUE THREAD

**Issue by whippett2000** [helgeerbe/picframe#108]
I wondered if you can help me.  I want to access photos stored on a password protected share on a NAS drive on the same wifi network as the Raspberry Pi.  What lines of code do I need to insert into the script?  I am assuming these configurations will need inserting in the configuration.yaml file?  This is for the Pi3D PictureFrame image viewer installed on my Raspberry Pi 3

**Comment by helgeerbe** [comment]
Hi @whippett2000 you have to mount your NAS share on your raspberry. Search on google `mounting a shared NAS folder to a Raspberry Pi` . In the configuration.yaml you can point the picture directory to your image folder on the mountpoint.

**Comment by paddywwoof** [comment]
I have added some code that should make mapping drives to subdirectories within ~/Pictures (as per your (Helge's) instructions and Jeff's and my suggestions) https://github.com/helgeerbe/picframe/issues/76

I will merge those changes into the dev branch tonight or tomorrow. (Also get v2.45 of pi3d up to pypi)

Paddy

**Comment by helgeerbe** [comment]
New release [2021.05.02](https://github.com/helgeerbe/picframe/wiki/Changelog) is published

**Comment by helgeerbe** [comment]
No more action on this issue. Guess I can close it.
