### ISSUE TITLE
exif_datetime format

### ISSUE THREAD

**Issue by junglebells** [helgeerbe/picframe#151]
I wanted to bring another topic to your attention. The following MQTT command is not working for me: 
mosquitto_pub -h localhost -t picframe/date_from -m "2021-01-01"

Looking at the DB, I noticed the exif_datetime to be in a numeric format (see screenshot)
<img width="591" alt="Screen Shot 2021-07-20 at 8 27 31 PM" src="https://user-images.githubusercontent.com/68487929/126426540-21bcf8d9-1bd2-4b16-b3bb-294843b56e2d.png">

Is this considered normal? Any tips of debugging the issue?
Thanks again for all your help.

**Comment by jgodfrey** [comment]
Hi @junglebells,

The dates in the database are stored in a Unix epoch time format, so what you show above is indeed normal. I don't have access to the code ATM so I can't offer much advice right now. I'll try take a look soon unless someone beats me to it.

**Comment by paddywwoof** [comment]
It would be easy to fix it to use - as well as : and / https://github.com/helgeerbe/picframe/blob/b0fddbb9df1b771a9133dc3dd5ea92c18b9165df/picframe/controller.py#L10

**Comment by junglebells** [comment]
Thanks @paddywwoof and @jgodfrey - I figured out the problem. It was an error at my end, I had a filter on, that I didn't realize.

Appreciate all your help and prompt responses.
