### ISSUE TITLE
Overlapping and cut-off overlay text 

### ISSUE THREAD

**Issue by jeffalperin** [helgeerbe/picframe#181]
I'm having several problems displaying overlay text information.  If the `show_text_sz` value is large enough (e.g. 50) and the amount of text is great enough, some info text fields are repeated (e.g. the beginning of the caption field) and/or cut-off when displayed.  

See attached screenshot for an example.

Is it possible to have the info text wrap onto a new line?  I've seen references to text wrapping in some old issues, but I don't see how to configure that.

I'm running on a rPi 4 (8gb) with a 4k display if that's relevant.

Thanks for any suggestions.

![info text issues2](https://user-images.githubusercontent.com/42316774/138616525-4c0f01d0-3f29-4af4-a7a7-f13c360452fb.jpg)

**Comment by helgeerbe** [comment]
Will be fixed in release 2021.11.04
