### ISSUE TITLE
Make setup more user friendly

### ISSUE THREAD

**Issue by helgeerbe** [helgeerbe/picframe#24]
Extend the -i option to configure `configuration.yaml`properly.
E. g. 

- set the correct paths.
- ask for locale

- offer to copy to copy 'picframe.service' to `~/.config/systemd/user` and enable it on boot time.

...

**Comment by helgeerbe** [comment]
Adding a quick hack for -i option
Creates `configuration.yaml` 
- set all paths to selected picframe_data directory
- ask for pic dir
- ask for deleted pic dir
- reads current locale and ask for it

Hope this makes setup more easy. Later on, we should move config to the database an make setting persistent.

**Comment by jgodfrey** [comment]
Sorry to be late on the requested PR review here... Minor, but I might suggest that the `start.py` script mention where the results of the process are stored (so, point to the `configuration.yaml` file).

**Comment by helgeerbe** [comment]
It das a `print("This will configure ", destination)` 
destination is the full path

**Comment by jgodfrey** [comment]
Yeah, I see that now. Cool - thanks.
