### ISSUE TITLE
Add improved support for auto-matting on non-HD resolutions

### ISSUE THREAD

**Issue by jgodfrey** [helgeerbe/picframe#28]
Currently, the auto-matting capabilities of PictureFrame have been designed for HD resolutions. While the matting will work for non-HD resolutions, it won't look exactly as intended. For example, on a 4k display, the matting decorations (bevels, shadows, ...) will be narrower than intended.

The fix here will involve a number of things, including:
 * Provide 4k versions of the ninepatch files used to create the decorations
 * Provide a mechanism to access the correct set of ninepatch files.
 * Calculate an internal "modifier" that can be used to auto-adjust appropriate matting properties based on the current resolution.

**Comment by jgodfrey** [comment]
Has anyone viewed the auto-mat results on a 4K display? While I can imagine what they look like (generally, too _narrow_ I assume), I've actually never seen them. I do have a 4K TV I could hook up to I guess - it's just not in a convenient location for dev work...

**Comment by jgodfrey** [comment]
Still curious here - has anyone tried the matting on a 4k display. As described above, I can imagine what it'll look like, but I've yet to see it.

**Comment by paddywwoof** [comment]
I too don't have a 4k screen.. but you might be able to specify the dimensions in the config file wider than the screen. I will try that out now on the RPi4

**Comment by jgodfrey** [comment]
I *do* have a 4k tv I could hook up to. So far, I've just been too lazy to do it... :)
