### ISSUE TITLE
Image not displaying on HDMI monitor

### ISSUE THREAD

**Issue by MDanihy** [helgeerbe/picframe#290]
The program appears to be running, but it is not displaying on an HDMI monitor.  I have another setup using an RPI touchscreen connected to the GPIO connector and that works fine.

**Comment by helgeerbe** [comment]
Hi @MDanihy do you have some more infos. Logfile? Without that information, I don't know how to support you.

**Comment by MDanihy** [comment]
Thanks for the reply,

I totally rebuilt the frame, not sure why there was no HDMI output at that time.


On Nov 24, 2022, at 11:53 AM, helgeerbe ***@***.******@***.***>> wrote:



Hi @MDanihy<https://github.com/MDanihy> do you have some more infos. Logfile? Without that information, I don't know how to support you.
