### ISSUE TITLE
Will Picture 

### ISSUE THREAD

**Issue by kpetersen8880** [helgeerbe/picframe#299]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**What are your OS, Python and picframe versions(please complete the following information):?**

- Hardware:
- OS: 
- Python: 
- picframe (run `picframe -v` if possible): 

```yaml
configuration.yaml goes here
```

````txt
log output goes here
````

**Additional context**

**Comment by helgeerbe** [comment]
Nothing in the description.
