### ISSUE TITLE
Detailed documentation?

### ISSUE THREAD

**Issue by raspitakesovertheworld** [helgeerbe/picframe#316]
I'm looking for a more verbose documentation that explains things in detail, where can I find it?
Many terms are not explained, for example what blur is for or why there is a folder for deleted pics (how do you delete them?)
Also, is there any other way to control this without using MQTT, like with a keyboard or buttons mapped via GPIO?

**Comment by jgodfrey** [comment]
Not sure if you've found the wiki or not, but it's probably the best documentation that's available. See [here](https://github.com/helgeerbe/picframe/wiki). There's some navigation in the right-hand panel. And, here's a direct link to the [configuration options page](https://github.com/helgeerbe/picframe/wiki/Configuration).

**Comment by raspitakesovertheworld** [comment]
Thank you, that is helpful.
