### ISSUE TITLE
Feature Request: GPIO Buttons

### ISSUE THREAD

**Issue by dexn** [helgeerbe/picframe#321]
Support GPIO buttons as inputs to toggle/select options like back, next, paused, display_is_on, power etc...

Possibility to use a single GPIO button for multiple actions with single/multi-press or timed press.

I currently use [gpiocmd by aheimsbakk](https://github.com/aheimsbakk/gpiocmd) to call curl. It would be nice to have something like this that's native in picframe to interact with it directly without using http or mqtt.

**Comment by paddywwoof** [comment]
@dexn My view would be that we should probably keep that functionality outside the "core" picframe. I'm in the process of setting something up for my frame in the kitchen (two years after I decided it needed to be done) and I will post the result. It will consist of:
```
1. very simple python script using gpiozero and paho mqtt to check pins and send messages to the picframe
2. a systemd process to start the script on startup
```
Paddy

**Comment by helgeerbe** [comment]
For those not using MQTT it might be easier if you use rest calls to the http interface.  So you don't have to set up a broker.

**Comment by paddywwoof** [comment]
@helgeerbe good point. Now you have suggested it that is certainly what I will use as the http interface is the way I communicate with the picture frame.

**Comment by paddywwoof** [comment]
I've just started using simple script below. It essentially just turns the picframe on if there's a make or break between GPIO4 and GND, using a PIR sensor, then turns it off after a while. Obviously pause, next, back, off wouldn't need the complication of the timer thread. I've not done much testing, so I will update this in a while and add examples of using other GPIO for different things and long presses etc, but you might be able to experiment with variations of what you're using now with gpiocmd
``` python
import gpiozero
import threading
import datetime
import time
import signal
from urllib import request

STAY_ON = datetime.timedelta(minutes=30)
URL = "http://localhost:9000"

# state info kept in a single object -> no mutating globals
class MovementTimer:
    def __init__(self):
        self.turn_off_time = datetime.datetime.now() + STAY_ON
        self.currently_on = True
        self.t = threading.Thread(target=self.background_timer, daemon=True)
        self.t.start()
        self.detector = gpiozero.Button(4) # pull-up default so short to GND with button
        self.detector.when_pressed = self.reset_timer # only need one or other
        self.detector.when_released = self.reset_timer # but.. belt and braces

    def reset_timer(self):
        # turn on if not already and reset turn off time
        self.turn_off_time = datetime.datetime.now() + STAY_ON
        if not self.currently_on:
            request.urlopen(f"{URL}?display_is_on=ON")
            self.currently_on = True

    def background_timer(self):
        # turns off after long inactivity
        while True:
            if self.currently_on and (self.turn_off_time - datetime.datetime.now()) < datetime.timedelta(seconds=1):
                request.urlopen(f"{URL}?display_is_on=OFF")
                self.currently_on = False
            time.sleep(5) # no need to check very often

timer = MovementTimer()

signal.pause() # effectively a wait-forever loop
```
and in `~/.config/systemd/user/check_gpio.service` (I used a different service so I could stop and start it independently)
```bash
[Unit]
Description=Check GPIO and send message to picframe http

[Service]
ExecStart=/bin/python3 ~/picframe_data/check_gpio.py  ### or wherever this is  
Restart=always

[Install]
WantedBy=default.target
```

Paddy
