### ISSUE TITLE
I any one able to help me with MQTT

### ISSUE THREAD

**Issue by GitRayc** [helgeerbe/picframe#357]
I really appreciate the digitalpictureframe.com web pages.   Thnaks

I am trying to get my hear around MQTT.   Using the web page:[
](https://www.thedigitalpictureframe.com/how-to-install-an-mqtt-broker-locally-on-your-digital-picture-frame-raspberry-pi/)
I have installed MQTT

I ran the suggested tests and all is working well.

in a shell window I ssh to my pi using my mac and I issue the command:
mosquitto_sub -h localhost -v -t frame_channel

It seems that this command makes the pi listen to the frame_channel

Now I go over to my pc and I enter the command:
mosquitto_pub -h localhost -t frame_channel -m "Hello Digital Picture Frame"

Any yea it works perfectly!

Now I want to send some commands from SimplePi on my ipad.

I send the command:
mosquitto_pub -h localhost -t picframe/subdirectory -m "Family"      # I have the subdirectory set up and named wiht pics in it

But nothing seems to happen.

My question is:
I the first example I told pi to listen to "frame_channel"    

But in the second example (from my ipad)  how does the pi know to listen to "picframe/subdirectory"

And if it is not told to listen to this specifcally is that why nothing seems to happen?

Ray

**Comment by jgodfrey** [comment]
I believe this topic (from your above  message):

`picframe/subdirectory`

should instead be:

`picframe/directory`

>  how does the pi know to listen to "picframe/subdirectory"

The picture frame software itself is listening for messages published to a number of "picframe/*" topics...
