### ISSUE TITLE
Blank screen after starting picframe.service on RPi5

### ISSUE THREAD

**Issue by HandsOnKatie** [helgeerbe/picframe#363]
Hi all, 

Just attempting to test this on a RPi5 and following the guide here:
https://www.thedigitalpictureframe.com/how-to-build-a-gorgeous-digital-photo-frame-with-a-raspberry-pi-based-on-2023-bookworm/

All appears to install/work fine, except when I start the service (either automatically on boot or manually), it displays a blank screen.

OS booting fine and console works fine, all services appear to be running fine - just getting a blank screen. Have an image in the Pictures directory (although assume the 'no picture' image should have appeared anyway).

RPi5 8gb
Raspberry Pi OS Bookworm Dec 2023
PictureFrame 2023
Raspberry Pi Imager 1.8.3

picframe version:  2023.07.26.post1+2.ge437440

Checking required packages......
PIL :  9.5.0
pi3d :  2.51
yaml :  6.0.1
paho.mqtt :  1.6.1
iptcinfo3 :  2.1.4
numpy :  1.26.2
ninepatch : installed, but no version info
pi_heif :  0.14.0
defusedxml :  0.7.1

Only change I've made vs the original instructions is changing the username from 'pi' to my own - I've doublechecked and think I've caught all these updates.

Any suggestions on how to debug?  Conscious RPi5 support is still in testing, so keen to check if it's something I've done or just a bug!

**Comment by paddywwoof** [comment]
I'm out at the moment but will work through Wolfgang's instructions later on Pi 5 to see if I can spot anything.

**Comment by HandsOnKatie** [comment]
I've tried adding: dtoverlay=vc4-fkms-v3d to the config.txt - this creates a small garbled square image in the middle of the screen, but nothing further?

**Comment by paddywwoof** [comment]
Hi, I came confirm that I have been using picframe with Pi5 and 64 bit desktop mainly fine. The issue is automatic starting and process ownership. Hopefully soluble!

**Comment by HandsOnKatie** [comment]
How odd - I've got it automatic start, so does this not work? Anything else you needed to do to configure?

**Comment by paddywwoof** [comment]
To clarify my earlier comment. I've been busying myself trying to get the screensaver to work (or specifically get the emulated mouse movement and key presses to wake the slideshow up again after the screensaver had cut in). I have been using the Raspberry Pi 5 which I set up with the `start_picframe.sh` and the `.config/wayfire.ini` but I wasn't focussed on getting the systemd start process running. Now that I quickly try that I find that I get a blank screen with a mouse arrow. I'm pretty sure I ran into this before and got it working but I can't remember the details so I will have to start again from scratch and figure it out.

A couple of things I have found: not having the `[core]` section in `.config/wayfire.ini` seems to allow picframe to start even when the desktop is running but including `[core]` causes problems. The `source` command is instrinsic to bash so leaving the `#!/bin/bash` from the first line of the start_picframe.sh script stops the python back end to run and produces a blank screen with a mouse arrow.

**Comment by HandsOnKatie** [comment]
Ah interesting and good to know it's not just me doing something silly! 

Will have a fiddle myself - it sounds like it should work if I switch off the systemd  start process

**Comment by paddywwoof** [comment]
Kate, I've just nipped through the process c.f. [@sapnho](https://github.com/sapnho) 's instructions and there are a couple of things that are probably relevant. Mainly **NB** the missing library files used by numpy and PIL `openblas0-pthread`, `gfortran5` and `openjp2-7` (Wolfgang, you probably need to mention those library files in your instructions). I also started with the 32 bit lite Bookworm which was dated 11th rather than 5th December (64bit works OK with picframe on Pi 3 and 4 but I'm just trying to eliminate variables one by one).

Here is the listing from my `.bash_history`
```bash
sudo apt update
sudo apt upgrade -y
sudo apt install python3-venv git libsdl2-dev wayfire wlr-randr -y
sudo raspi-config
mkdir venv_picframe
python -m venv /home/pi/venv_picframe
source venv_picframe/bin/activate
python -m pip install git+https://github.com/helgeerbe/picframe@sdl2
sudo apt install libopenblas0-pthread libgfortran5 libopenjp2-7 -y
mkdir {Pictures,DeletedPictures}
picframe -i /home/pi/
nano picframe_data/config/configuration.yaml
nano start_picframe.sh
chmod +x start_picframe.sh
mkdir .config
nano .config/wayfire.ini
mkdir .config/systemd/user -p
nano .config/systemd/user/picframe.service
systemctl --user enable picframe.service
system reboot
sudo reboot
```
To stop wayfire I open a new terminal with Ctr+Alt+F2 and log in as pi, then
```bash
wayfire
pidof wayfire
kill 1267
```
swap back with Ctr+Alt+F1

To start with I used a "cut down" version that would drop back to using xwayland
start_picframe.sh
```bash
#!/bin/bash
source /home/pi/venv_picframe/bin/activate
sleep 2
picframe &
```
.config/wayfire.ini
```ini
[core]
plugins = autostart

[autostart]
picframe = /home/pi/start_picframe.sh
```
But when I added back in the lines `export SDL_VIDEODRIVER=wayland` and `xwayland = false` it all still worked fine. (I didn't bother with wlr-randr as it doesn't seem to switch the screen back on when we need it to)

Paddy

**Comment by paddywwoof** [comment]
**NB** also @helgeerbe and @sapnho the step of installing, uninstalling and reinstalling picframe@sdl2 is not needed. You can just do it in one line
```bash
python -m pip install git+https://github.com/helgeerbe/picframe@sdl2
```

**Comment by HandsOnKatie** [comment]
Ah thanks Paddywwoof - various missed bits then! 

Ok, have gone through your .bash_history and filled the blanks and getting different error now - on running start_picframe.sh, 'I get failed to connect to display' X11 needs to be running?

**Comment by paddywwoof** [comment]
That sounds like an error from trying to use xserver. Have you set use_sdl2 to True in the configuration.yaml file?

**Comment by paddywwoof** [comment]
Also, with the lite version of the OS I think you need to start Wayland going and allow that to spawn start_picframe.sh I would use the systemctl stop and start commands to do that. You can also run `wayfire` from a command prompt but you need to have everything else debugged first. And stopping it from another session using the pidof then kill as I mentioned in my post

**Comment by HandsOnKatie** [comment]
<sigh> - sorry, forgot that my configuration.yaml would have been overwritten by going through above process! <faceplant!>

Ok, interested now - still getting an initial 'failed to connect to display', but it seems to run and then I get the following screen:
![PXL_20231223_124137708](https://github.com/helgeerbe/picframe/assets/152065789/54351200-0099-405b-983f-b16bf15df467)

Can obviously do a clean wipe, but curious to pin down what's missing now - else I'll never learn!

Do you think this could be the wayfire point you mention above?

PS - totally agree regarding the SD card images - think I'll be doing this myself anyway as plan to create 6-7 frames at least around the house, so we might as well do it for everyone!  Also means you guys will spend much less time debugging daft user errors.....erm... like dimwitted women like me.... ;)

**Comment by paddywwoof** [comment]
At some point recently I got a similar effect... but now I'm kicking myself for not making a note of what caused it!! It looks like a mismatch between the real screen dimensions and whatever the GPU driver thinks they are. Do you know what the screen size is?

Is the dtoverlay=vc4.. still in effect? 

All this messing around must be Very frustrating for you but it's all adding to information for sorting things out more thoroughly so thank you for persisting. There are so many variables it's quite a nightmare to set it up reliably!

**Comment by HandsOnKatie** [comment]
No worries at all - glad to help debug (as I say, easy enough for me to just wipe and start from scratch, but we'd not understand which element fixes what if I did that!)

Ah bingo, you're right - played around with the /boot/config.txt and solved by setting dtoverlay=vc4-kms-v3d to dtoverlay=vc4-fkms-v3d  (I had done this previously, but obviously got reset) - obvious when you pointed out, but hopefully useful to know the symptom next time someone has it!

Frame working beautifully now - time to build some frames in time for Christmas!

I'll get working on a video guide in the new year and definitely keen to create a standardised set of images (so might hold fire on any walkthroughs until that as that'd be a wildly simpler approach for folks to use!)

I'll also create some standardised 3d printed parts I think for folks to use to fit their pi to the frame and so on to save them some time!

Keep up the great work and thanks again for all your help!!

**Comment by paddywwoof** [comment]
Good that you found a fix. But... confusing that my /boot/config txt has
```
dtoverlay=vc4-kms-v3d
```
I'm not really sure what this does with Pi 5 to be honest - I probably ought to do some reading up. At some stage in the past there was more comprehensive support for true OpenGL (as opposed to the OpenGLES hardware used by mobile GPUs) done by software but at the expense of speed. Might be less relevant on Pi 5 I will try some FPS test with and without the f

Paddy

**Comment by HandsOnKatie** [comment]
Yes, bit of a mystery that one - taking out again causes the problem. I'm stepping through just out of curiosity to check if it's a combination of errors that are resolving each other...!

Also portrait mode appears to not work, have tried instructions here for Rpi4:
https://www.thedigitalpictureframe.com/raspberry-pi-digital-picture-frame-portrait-orientation/

And I get sudo: xinit: command not found when I run the second part?

**Comment by paddywwoof** [comment]
Katie, someone has recently reported and solved an issue relating to portrait orientation. I don't know of Wolfgang has incorated that info in his website yet. I will have a scan back whe. I get a chance later on.

**Comment by HandsOnKatie** [comment]
Ah no problem then - I tried installing xinit manually, but that spits out:

xinit: giving upinated with error (1). Closing log file.log" for additional information.vices console=ttyAMA10,115200 console=tty1 root=PARTUUID=4                                   xinit: unable to connect to X server: Connection refused
xinit: server error

So might wait to see what Wolfgang thinks if a known issue!

**Comment by HandsOnKatie** [comment]
Ah - updating start_picframe.sh to:

wlr-randr --output HDMI-A-1 --transform 270 --on

Did the trick - portrait mode working!

(note you'll need to update cmdline.txt also to set the right direction here too)

**Comment by sapnho** [comment]
Hi @paddywwoof Got my Pi5 yesterday and will start testing right away when I get back from family after Christmas!

**Comment by sapnho** [comment]
> NB also @helgeerbe and @sapnho the step of installing, uninstalling and reinstalling picframe@sdl2 is not needed. You can just do it in one line

Have just made the changes and also the others that you suggested.

**Comment by sapnho** [comment]
> Katie, someone has recently reported and solved an issue relating to portrait orientation. I don't know of Wolfgang has incorated that info in his website yet. I will have a scan back whe. I get a chance later on.

Yes, I'll wait until we have everything in Bookworm going fine and will then do a general update of the articles.
