### ISSUE TITLE
paho-mqtt v2.0.0 compatibility 

### ISSUE THREAD

**Issue by junglebells** [helgeerbe/picframe#380]
Hello, it seems paho recently released a new version that is breaking fresh install of picframe (if you enable mqtt)

I was able to make it work by installing version 1.6.1 of paho-mqtt. However, this might need a better solution.

Thanks for your help. Best regards!

**Comment by Vinswede** [comment]
Found it: sudo pip3 install paho-mqtt-1.6.1
MQTT control via Home Assistant working perfectly. 
Thanks 👍
