### ISSUE TITLE
Updating Picframe to latest version on Pi5

### ISSUE THREAD

**Issue by Notrial** [helgeerbe/picframe#395]
Does anyone know the proper procedure to update from few versions back to the latest one through SSH on Pi5?
Will I have to reconfigure everything or does it maintain config files?

I am on MacOS terminal and typing sudo pip3 install picframe --upgrade just gives me this.

![image](https://github.com/user-attachments/assets/48745cea-0fa7-4a5c-b4b4-8a2bb5a26eb5)

Also the commans like picframe -v do nothing:
![image](https://github.com/user-attachments/assets/c848e033-249f-4873-b999-dc2182ea0fcd)

**Comment by paddywwoof** [comment]
Hi, did you originally install picframe with a virtual environment. There have been various versions of setting up picframe on the RPi5 and (some?) use `venv`. If you originally used venv then you will need to activate it before using pip. something like
```source /home/pi/venv_picframe/bin/activate```

**Comment by Notrial** [comment]
that is it! Thank you so much.

**Comment by Notrial** [comment]
@paddywwoof btw. should I backup anything before I run the upgrade command? Will it overwrite the config files?

Cheers!

**Comment by paddywwoof** [comment]
Well I would *never* suggest not backing up... however pip should only write over the installed files and I think that has a file `.../config/confguration_example.yaml` that you would have copied to `configuration.yaml`, which should remain unscathed. Just to be on the safe side I would probably copy that latter file to your mac at the very least!

**Comment by Notrial** [comment]
I finally got around to do this, but it seems I spoke too soon...
Although picframe -v works after source /home/pi/venv_picframe/bin/activate, unfortunately sudo pip3 install picframe --upgrade gives me the same error as before (This environment is externally managed...).

Do I have to type out this upgrade command in a different way?
