### ISSUE TITLE
Error with Pillow Install

### ISSUE THREAD

**Issue by jhopkins213** [helgeerbe/picframe#422]
When trying to install picframe I get this 

 pip install picframe
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting picframe
  Using cached https://www.piwheels.org/simple/picframe/picframe-2024.11.1-py3-n                                                                          one-any.whl (3.3 MB)
Collecting Pillow>=10.2.0 (from picframe)
  Using cached pillow-11.0.0.tar.gz (46.7 MB)
  Installing build dependencies ... -Pillodone
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting defusedxml (from picframe)
  Using cached https://www.piwheels.org/simple/defusedxml/defusedxml-0.7.1-py2.p                                                                          y3-none-any.whl (25 kB)
Collecting pi3d>=2.52 (from picframe)
  Using cached https://www.piwheels.org/simple/pi3d/pi3d-2.52-py3-none-any.whl (                                                                          256 kB)
Requirement already satisfied: PyYAML in ./venv_picframe/lib/python3.11/site-pac                                                                          kages (from picframe) (6.0.2)
Collecting paho-mqtt (from picframe)
  Using cached https://www.piwheels.org/simple/paho-mqtt/paho_mqtt-2.1.0-py3-non                                                                          e-any.whl (67 kB)
Collecting IPTCInfo3 (from picframe)
  Using cached https://www.piwheels.org/simple/iptcinfo3/IPTCInfo3-2.1.4-py3-non                                                                          e-any.whl (12 kB)
Collecting numpy (from picframe)
  Using cached https://www.piwheels.org/simple/numpy/numpy-2.1.3-cp311-cp311-lin                                                                          ux_armv7l.whl (6.0 MB)
Collecting ninepatch>=0.2.0 (from picframe)
  Using cached ninepatch-0.2.0-py3-none-any.whl.metadata (4.9 kB)
Collecting pi-heif>=0.8.0 (from picframe)
  Using cached pi_heif-0.21.0.tar.gz (16.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pysdl2 (from pi3d>=2.52->picframe)
  Using cached https://www.piwheels.org/simple/pysdl2/PySDL2-0.9.16-py3-none-any                                                                          .whl (580 kB)
Using cached ninepatch-0.2.0-py3-none-any.whl (9.1 kB)
Building wheels for collected packages: pi-heif, Pillow
  Building wheel for pi-heif (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pi-heif (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [75 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build/lib.linux-aarch64-cpython-311/pi_heif
      copying pi_heif/misc.py -> build/lib.linux-aarch64-cpython-311/pi_heif
      copying pi_heif/constants.py -> build/lib.linux-aarch64-cpython-311/pi_hei                                                                          f
      copying pi_heif/_lib_info.py -> build/lib.linux-aarch64-cpython-311/pi_hei                                                                          f
      copying pi_heif/_version.py -> build/lib.linux-aarch64-cpython-311/pi_heif
      copying pi_heif/_deffered_error.py -> build/lib.linux-aarch64-cpython-311/                                                                          pi_heif
      copying pi_heif/__init__.py -> build/lib.linux-aarch64-cpython-311/pi_heif
      copying pi_heif/as_plugin.py -> build/lib.linux-aarch64-cpython-311/pi_hei                                                                          f
      copying pi_heif/options.py -> build/lib.linux-aarch64-cpython-311/pi_heif
      copying pi_heif/heif.py -> build/lib.linux-aarch64-cpython-311/pi_heif
      copying pi_heif/HeifImagePlugin.py -> build/lib.linux-aarch64-cpython-311/                                                                          pi_heif
      copying pi_heif/AvifImagePlugin.py -> build/lib.linux-aarch64-cpython-311/                                                                          pi_heif
      running build_ext
      Package libheif was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libheif.pc'
      to the PKG_CONFIG_PATH environment variable
      Package 'libheif', required by 'virtual:world', not found
      Package heif was not found in the pkg-config search path.
      Perhaps you should add the directory containing `heif.pc'
      to the PKG_CONFIG_PATH environment variable
      Package 'heif', required by 'virtual:world', not found

      The headers or library files could not be found for libheif,
      a required dependency when compiling Pillow-Heif from source.

      Please see the install instructions at:
         https://pillow-heif.readthedocs.io/en/latest/installation.html

      Looking for `libheif` using pkg-config.
      Looking for `heif` using pkg-config.
      Checking for include file 'heif.h' in '/home/pi/venv_picframe/include'
      Checking for include file 'heif.h' in '/home/pi/venv_picframe/include/libh                                                                          eif'
      Checking for include file 'heif.h' in '/usr/local/include'
      Checking for include file 'heif.h' in '/usr/local/include/libheif'
      Checking for include file 'heif.h' in '/usr/include'
      Checking for include file 'heif.h' in '/usr/include/libheif'
      Checking for include file 'heif.h' in '/home/pi/venv_picframe/include'
      Checking for include file 'heif.h' in '/home/pi/venv_picframe/include/libh                                                                          eif'
      Checking for include file 'heif.h' in '/usr/include/python3.11'
      Checking for include file 'heif.h' in '/usr/include/python3.11/libheif'
      Traceback (most recent call last):
        File "/home/pi/venv_picframe/lib/python3.11/site-packages/pip/_vendor/py                                                                          project_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/pi/venv_picframe/lib/python3.11/site-packages/pip/_vendor/py                                                                          project_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/pi/venv_picframe/lib/python3.11/site-packages/pip/_vendor/py                                                                          project_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-h2cfmmp1/overlay/lib/python3.11/site-packages/s                                                                          etuptools/build_meta.py", line 438, in build_wheel
          return _build(['bdist_wheel', '--dist-info-dir', str(metadata_director                                                                          y)])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                          ^^^^
        File "/tmp/pip-build-env-h2cfmmp1/overlay/lib/python3.11/site-packages/s                                                                          etuptools/build_meta.py", line 426, in _build
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-h2cfmmp1/overlay/lib/python3.11/site-packages/s                                                                          etuptools/build_meta.py", line 407, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-h2cfmmp1/overlay/lib/python3.11/site-packages/s                                                                          etuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-h2cfmmp1/overlay/lib/python3.11/site-packages/s                                                                          etuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 289, in <module>
      RequiredDependencyException:

      The headers or library files could not be found for libheif,
      a required dependency when compiling Pillow-Heif from source.

      Please see the install instructions at:
         https://pillow-heif.readthedocs.io/en/latest/installation.html

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem wit                                                                          h pip.
  ERROR: Failed building wheel for pi-heif
  Building wheel for Pillow (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for Pillow (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [217 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/IcoImagePlugin.py -> build/lib.linux-aarch64-cpython-311/P                                                                          IL
      copying src/PIL/ImageShow.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/PSDraw.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/ImageMorph.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/TiffTags.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/_binary.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/WmfImagePlugin.py -> build/lib.linux-aarch64-cpython-311/P                                                                          IL
      copying src/PIL/PcxImagePlugin.py -> build/lib.linux-aarch64-cpython-311/P                                                                          IL
      copying src/PIL/ImageDraw2.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/TiffImagePlugin.py -> build/lib.linux-aarch64-cpython-311/                                                                          PIL
      copying src/PIL/PdfParser.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/GbrImagePlugin.py -> build/lib.linux-aarch64-cpython-311/P                                                                          IL
      copying src/PIL/PpmImagePlugin.py -> build/lib.linux-aarch64-cpython-311/P                                                                          IL
      copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-aarch64-cpython-                                                                          311/PIL
      copying src/PIL/PcfFontFile.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/FontFile.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/ImageCms.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/FpxImagePlugin.py -> build/lib.linux-aarch64-cpython-311/P                                                                          IL
      copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-aarch64-cpython-                                                                          311/PIL
      copying src/PIL/SgiImagePlugin.py -> build/lib.linux-aarch64-cpython-311/P                                                                          IL
      copying src/PIL/WebPImagePlugin.py -> build/lib.linux-aarch64-cpython-311/                                                                          PIL
      copying src/PIL/PngImagePlugin.py -> build/lib.linux-aarch64-cpython-311/P                                                                          IL
      copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-aarch64-cpython-311/                                                                          PIL
      copying src/PIL/_typing.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/ExifTags.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/XpmImagePlugin.py -> build/lib.linux-aarch64-cpython-311/P                                                                          IL
      copying src/PIL/SunImagePlugin.py -> build/lib.linux-aarch64-cpython-311/P                                                                          IL
      copying src/PIL/ImagePalette.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/ImageWin.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/ImageGrab.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/JpegImagePlugin.py -> build/lib.linux-aarch64-cpython-311/                                                                          PIL
      copying src/PIL/ImageDraw.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/GimpPaletteFile.py -> build/lib.linux-aarch64-cpython-311/                                                                          PIL
      copying src/PIL/IptcImagePlugin.py -> build/lib.linux-aarch64-cpython-311/                                                                          PIL
      copying src/PIL/FitsImagePlugin.py -> build/lib.linux-aarch64-cpython-311/                                                                          PIL
      copying src/PIL/QoiImagePlugin.py -> build/lib.linux-aarch64-cpython-311/P                                                                          IL
      copying src/PIL/ImageFile.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/ImageEnhance.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/_version.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/XbmImagePlugin.py -> build/lib.linux-aarch64-cpython-311/P                                                                          IL
      copying src/PIL/DcxImagePlugin.py -> build/lib.linux-aarch64-cpython-311/P                                                                          IL
      copying src/PIL/MpegImagePlugin.py -> build/lib.linux-aarch64-cpython-311/                                                                          PIL
      copying src/PIL/PdfImagePlugin.py -> build/lib.linux-aarch64-cpython-311/P                                                                          IL
      copying src/PIL/PcdImagePlugin.py -> build/lib.linux-aarch64-cpython-311/P                                                                          IL
      copying src/PIL/ImageStat.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/GimpGradientFile.py -> build/lib.linux-aarch64-cpython-311                                                                          /PIL
      copying src/PIL/ImtImagePlugin.py -> build/lib.linux-aarch64-cpython-311/P                                                                          IL
      copying src/PIL/FtexImagePlugin.py -> build/lib.linux-aarch64-cpython-311/                                                                          PIL
      copying src/PIL/ImageFilter.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/ImageColor.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/ImageTk.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/PalmImagePlugin.py -> build/lib.linux-aarch64-cpython-311/                                                                          PIL
      copying src/PIL/GdImageFile.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/WalImageFile.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-aarch64-cpython-3                                                                          11/PIL
      copying src/PIL/TarIO.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/ImageFont.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/_util.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/ImageMath.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/BmpImagePlugin.py -> build/lib.linux-aarch64-cpython-311/P                                                                          IL
      copying src/PIL/ImageTransform.py -> build/lib.linux-aarch64-cpython-311/P                                                                          IL
      copying src/PIL/ContainerIO.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/_tkinter_finder.py -> build/lib.linux-aarch64-cpython-311/                                                                          PIL
      copying src/PIL/MspImagePlugin.py -> build/lib.linux-aarch64-cpython-311/P                                                                          IL
      copying src/PIL/features.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/BdfFontFile.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-aarch64-cpython-31                                                                          1/PIL
      copying src/PIL/ImageMode.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/CurImagePlugin.py -> build/lib.linux-aarch64-cpython-311/P                                                                          IL
      copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-aarch64-cpython-31                                                                          1/PIL
      copying src/PIL/PsdImagePlugin.py -> build/lib.linux-aarch64-cpython-311/P                                                                          IL
      copying src/PIL/__init__.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/__main__.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/PaletteFile.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-aarch64-cpython-                                                                          311/PIL
      copying src/PIL/Image.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-aarch64-cpython-31                                                                          1/PIL
      copying src/PIL/ImagePath.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/MicImagePlugin.py -> build/lib.linux-aarch64-cpython-311/P                                                                          IL
      copying src/PIL/ImageSequence.py -> build/lib.linux-aarch64-cpython-311/PI                                                                          L
      copying src/PIL/_deprecate.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/PixarImagePlugin.py -> build/lib.linux-aarch64-cpython-311                                                                          /PIL
      copying src/PIL/FliImagePlugin.py -> build/lib.linux-aarch64-cpython-311/P                                                                          IL
      copying src/PIL/ImageOps.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/GifImagePlugin.py -> build/lib.linux-aarch64-cpython-311/P                                                                          IL
      copying src/PIL/report.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/BlpImagePlugin.py -> build/lib.linux-aarch64-cpython-311/P                                                                          IL
      copying src/PIL/MpoImagePlugin.py -> build/lib.linux-aarch64-cpython-311/P                                                                          IL
      copying src/PIL/ImImagePlugin.py -> build/lib.linux-aarch64-cpython-311/PI                                                                          L
      copying src/PIL/ImageQt.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/JpegPresets.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/TgaImagePlugin.py -> build/lib.linux-aarch64-cpython-311/P                                                                          IL
      copying src/PIL/DdsImagePlugin.py -> build/lib.linux-aarch64-cpython-311/P                                                                          IL
      copying src/PIL/ImageChops.py -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/EpsImagePlugin.py -> build/lib.linux-aarch64-cpython-311/P                                                                          IL
      running egg_info
      writing src/pillow.egg-info/PKG-INFO
      writing dependency_links to src/pillow.egg-info/dependency_links.txt
      writing requirements to src/pillow.egg-info/requires.txt
      writing top-level names to src/pillow.egg-info/top_level.txt
      reading manifest file 'src/pillow.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.c'
      warning: no files found matching '*.h'
      warning: no files found matching '*.sh'
      warning: no files found matching '*.txt'
      warning: no files found matching '.flake8'
      warning: no previously-included files found matching '.appveyor.yml'
      warning: no previously-included files found matching '.clang-format'
      warning: no previously-included files found matching '.coveragerc'
      warning: no previously-included files found matching '.editorconfig'
      warning: no previously-included files found matching '.readthedocs.yml'
      warning: no previously-included files found matching 'codecov.yml'
      warning: no previously-included files found matching 'renovate.json'
      warning: no previously-included files matching '.git*' found anywhere in d                                                                          istribution
      warning: no previously-included files matching '*.so' found anywhere in di                                                                          stribution
      no previously-included directories found matching '.ci'
      no previously-included directories found matching 'wheels'
      adding license file 'LICENSE'
      writing manifest file 'src/pillow.egg-info/SOURCES.txt'
      copying src/PIL/_imaging.pyi -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/_imagingcms.pyi -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/_imagingft.pyi -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/_imagingmath.pyi -> build/lib.linux-aarch64-cpython-311/PI                                                                          L
      copying src/PIL/_imagingmorph.pyi -> build/lib.linux-aarch64-cpython-311/P                                                                          IL
      copying src/PIL/_imagingtk.pyi -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/_webp.pyi -> build/lib.linux-aarch64-cpython-311/PIL
      copying src/PIL/py.typed -> build/lib.linux-aarch64-cpython-311/PIL
      running build_ext

      The headers or library files could not be found for jpeg,
      a required dependency when compiling Pillow from source.

      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation/basic-installation                                                                          .html

      Traceback (most recent call last):
        File "<string>", line 1026, in <module>
        File "/tmp/pip-build-env-9kjeiiqx/overlay/lib/python3.11/site-packages/s                                                                          etuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-9kjeiiqx/overlay/lib/python3.11/site-packages/s                                                                          etuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-9kjeiiqx/overlay/lib/python3.11/site-packages/s                                                                          etuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-9kjeiiqx/overlay/lib/python3.11/site-packages/s                                                                          etuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-9kjeiiqx/overlay/lib/python3.11/site-packages/s                                                                          etuptools/dist.py", line 995, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-9kjeiiqx/overlay/lib/python3.11/site-packages/s                                                                          etuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-9kjeiiqx/overlay/lib/python3.11/site-packages/s                                                                          etuptools/command/bdist_wheel.py", line 381, in run
          self.run_command("build")
        File "/tmp/pip-build-env-9kjeiiqx/overlay/lib/python3.11/site-packages/s                                                                          etuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-9kjeiiqx/overlay/lib/python3.11/site-packages/s                                                                          etuptools/dist.py", line 995, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-9kjeiiqx/overlay/lib/python3.11/site-packages/s                                                                          etuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-9kjeiiqx/overlay/lib/python3.11/site-packages/s                                                                          etuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-9kjeiiqx/overlay/lib/python3.11/site-packages/s                                                                          etuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-9kjeiiqx/overlay/lib/python3.11/site-packages/s                                                                          etuptools/dist.py", line 995, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-9kjeiiqx/overlay/lib/python3.11/site-packages/s                                                                          etuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-9kjeiiqx/overlay/lib/python3.11/site-packages/s                                                                          etuptools/command/build_ext.py", line 99, in run
          _build_ext.run(self)
        File "/tmp/pip-build-env-9kjeiiqx/overlay/lib/python3.11/site-packages/s                                                                          etuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "<string>", line 845, in build_extensions
      RequiredDependencyException: jpeg

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/home/pi/venv_picframe/lib/python3.11/site-packages/pip/_vendor/py                                                                          project_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/pi/venv_picframe/lib/python3.11/site-packages/pip/_vendor/py                                                                          project_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/pi/venv_picframe/lib/python3.11/site-packages/pip/_vendor/py                                                                          project_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-xdgywips/pillow_5582eaa966774792b8ce511f0a944703/                                                                          _custom_build/backend.py", line 26, in build_wheel
          return super().build_wheel(wheel_directory, config_settings, metadata_                                                                          directory)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                          ^^^^^^^^^^
        File "/tmp/pip-build-env-9kjeiiqx/overlay/lib/python3.11/site-packages/s                                                                          etuptools/build_meta.py", line 438, in build_wheel
          return _build(['bdist_wheel', '--dist-info-dir', str(metadata_director                                                                          y)])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                          ^^^^
        File "/tmp/pip-build-env-9kjeiiqx/overlay/lib/python3.11/site-packages/s                                                                          etuptools/build_meta.py", line 426, in _build
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-9kjeiiqx/overlay/lib/python3.11/site-packages/s                                                                          etuptools/build_meta.py", line 407, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-install-xdgywips/pillow_5582eaa966774792b8ce511f0a944703/                                                                          _custom_build/backend.py", line 20, in run_setup
          return super().run_setup(setup_script)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-9kjeiiqx/overlay/lib/python3.11/site-packages/s                                                                          etuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 1042, in <module>
      RequiredDependencyException:

      The headers or library files could not be found for jpeg,
      a required dependency when compiling Pillow from source.

      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation/basic-installation                                                                          .html

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem wit                                                                          h pip.
  ERROR: Failed building wheel for Pillow
Failed to build pi-heif Pillow
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based p                                                                          rojects (pi-heif, Pillow)

**Comment by jhopkins213** [comment]
I appologize didnt install the 64 bit version this can be closed

**Comment by paddywwoof** [comment]
@jhopkins213 it's really annoying that PIL insulation fails with the 32 bit OS because of missing heif headers. That's the 'default' version of the OS (ie if you buy a preinstalled SD card) to run on all versions of raspberry pi. I might see if I can raise it as an issue somewhere... not sure where though.

**Comment by paddywwoof** [comment]
@jhopkins213 to add a little to this thread in case someone else happens across it with the same error messages. I don't think there is a `libheif` shared library compiled in the debian repositories for the 32 bit arm target. I've tried compiling it but ended up in dependency hell. BUT it might very well be possible to install picframe without heif support by cloning the repository to your 32 bit SD card, then taking the relevant out of the `pyproject.toml` file. i.e. follow the normal instructions on [Wolfgang's site](https://www.thedigitalpictureframe.com/how-to-build-the-best-raspberry-pi-digital-picture-frame-with-bookworm-and-pi3d-picframe-2024-edition/) (you will have to do the manual version rather than use the one-shot script) up to `pip install picframe` but instead
```bash
cd ~
git clone https://github.com/helgeerbe/picframe.git
cd picframe
nano pyproject.toml # delete the line, around #45 "pi_heif>=0.8.0" .. Ctrl-S, Ctrl-X
python -m pip install -e .
```
NB the last line has a critical `.` on the end of it. This will install the code from the local repo in `/home/pi/picframe`. If there is an update in the future you should be able to navigate to the directory and `git pull` to update to the latest version then. `python -m pip install -e . --upgrade`
