### ISSUE TITLE
enhance configure does not expand relativ path

### ISSUE THREAD

**Issue by helgeerbe** [helgeerbe/picframe#50]
If using `picframe -i .` the path is not expanded to absolute path. So it will work only, if current directory is pi's home directory

**Comment by helgeerbe** [comment]
pip install picframe==2021.2.27a3 fixed it

**Comment by sapnho** [comment]
What is the best way to update for users?

**Comment by helgeerbe** [comment]
never tried this `pip install picframe --upgrade`
but with the pre releases you have to uninstall and install
`pip uninstall picframe`
`pip install picframe`

**Comment by helgeerbe** [comment]
picframe_date untouched. but when you run `picframe -i .` save your configuration.yaml. this will be overwritten.

**Comment by sapnho** [comment]
>  pip uninstall picframe
Skipping picframe as it is not installed.

**Comment by helgeerbe** [comment]
ensure you use python3 so use `python3 -m pip uninstall picframe`
