### ISSUE TITLE
in configuration_example.yaml missing config value for mat_type

### ISSUE THREAD

**Issue by helgeerbe** [helgeerbe/picframe#67]
Release: 2021.03.10

I found in the wiki the mat_type value "float_color_wrap". This is not referenced in 'configuration_example.yaml'
Is this a valid value?

**Comment by jgodfrey** [comment]
Yes, it's a valid value. Obviously, it didn't get transferred into the description in the sample file...

The value list is as follows:

`self.__mat_types = ['float', 'float_polaroid', 'float_color_wrap', 'single_bevel', 'double_bevel', 'double_flat']`

**Comment by jgodfrey** [comment]
Just pushed a change to `dev`
