### ISSUE TITLE
Does the Ken Burns effect still work?

### ISSUE THREAD

**Issue by sapnho** [helgeerbe/picframe#70]
I wonder if this still works? 

I set it to "True" but the image doesn't move. I tried with and without matting.

**Comment by sapnho** [comment]
Ah. just saw some movement! It is super slow that's why I thought it stopped working altogether.

**Comment by paddywwoof** [comment]
Yes, it's quite effective over long show times, so long as the image subject is mainly in the middle of the picture. With portrait images though, there is normally a period when everyone looses their head!
