### ISSUE TITLE
Remote control matting on/off

### ISSUE THREAD

**Issue by sapnho** [helgeerbe/picframe#83]
It would be very neat if matting on/off was one day included in the mqtt remote control settings.

**Comment by paddywwoof** [comment]
I don't think this would be difficult to do. It just needs a method  `ViewerDisplay.set_mat_image_control_values()` (or maybe just modify and reuse the exisiting `__get_mat_image_control_values()`) and a method in `Controller`. And methods in interface_mqtt and interface_http! So, easy to do but quite a few files updated, maybe roll it into an update with other things and make sure it's tested.

**Comment by sapnho** [comment]
Great, thanks. Obviously not urgent, but nice to have.

**Comment by sapnho** [comment]
And to build on this enhancement wishlist, being able to remotely change the matting style via a dropdown menu in Home Assistant would be swell! :-)

**Comment by helgeerbe** [comment]
Included in release 2021.11.04
