### ISSUE TITLE
Matting Proportions

### ISSUE THREAD

**Issue by sapnho** [helgeerbe/picframe#84]
Maybe it's a feature that I don't yet understand and not a bug but I was wondering how the proportions in matting work. 

I have a 1920x1200px frame and an 1920x1200px image. When I activate matting with double_float, I expected that the matting was proportional to the image size. But it looks like this where the distances to the edge are uneven:
 
![IMG_4785](https://user-images.githubusercontent.com/33040431/111900640-0747a380-8a34-11eb-9faf-4e2d99eab4fb.jpeg)

**Comment by paddywwoof** [comment]
If the distances to the edge were the same top v. sides then you would have to crop or fill. i.e. 50 pixels all round would leave 1820x1100 so your image would be scaled to either 1820x1137.5 (cropped) or 1760x1100 (gaps)

**Comment by jgodfrey** [comment]
Yep, Paddy's correct. If you have an image that matches the aspect of your display, and then add a consistent border around it, the resulting image no longer matches the display's aspect ratio. That leads to the "uneven" borders. So, not a bug.

**Comment by sapnho** [comment]
Yes, math is hard to beat! :-)

**Comment by sapnho** [comment]
> PS did you specify that mat colour - it doesn't look like one that would be chosen by the algorithm?

No, I didn't specify it. Sometimes it has an artistic mind of its own!

**Comment by jgodfrey** [comment]
> No, I didn't specify it. Sometimes it has an artistic mind of its own!

What a great result though. That looks *really* nice!

**Comment by sapnho** [comment]
It does. The matting feature is superb!

**Comment by jgodfrey** [comment]
Seems like this issue can be closed?
