### ISSUE TITLE
Location data missing in database

### ISSUE THREAD

**Issue by sapnho** [helgeerbe/picframe#97]
I had a look at my (digital picture frame in the living room) database with the DB Browser. There are about 1,250 photos in there. All, except for a few exceptions, have GPS coordinates. Yet about 300 of them don't have an identified location.

I was trying to identify a pattern, but couldn't find one. I wonder if anybody else has come across this.

<img width="1971" alt="Bildschirmfoto 2021-04-04 um 08 15 58" src="https://user-images.githubusercontent.com/33040431/113500420-1e02f580-951e-11eb-9a73-83179386faba.png">

**Comment by paddywwoof** [comment]
That is strange, assuming they've all been displayed. (To start with no images have location info) Did you notice it from seeing photos on the display with no location?

Is the internet connection reliable for the picframe? If it's intermittent then I would expect the locations to be filled in eventually.

**Comment by sapnho** [comment]
> That is strange, assuming they've all been displayed. (To start with no images have location info) Did you notice it from seeing photos on the display with no location?

I will pull these photos over to my Test Pi and see what happens. And yes, the playlist has been circulating for quite some time.

> Is the internet connection reliable for the picframe? If it's intermittent then I would expect the locations to be filled in eventually.

Very much so. We have 100 M/bit internet and the router is 4 meters away from the frame. Signal strength is strong.

**Comment by sapnho** [comment]
Ok, so I imported the images on my Test Pi and let it run for a while. All 1250 images were recognized with the location.
Strange.

**Comment by sapnho** [comment]
Is the DB actually deleted when upgrading PictureFrame?

**Comment by paddywwoof** [comment]
I don't think it is. That certainly wasn't the idea.

**Comment by sapnho** [comment]
Ok, good to know. Just trying to understand the root cause of the issue.

**Comment by helgeerbe** [comment]
Is there anything left to do?

**Comment by helgeerbe** [comment]
@sapnho Can we close this?

**Comment by sapnho** [comment]
Yes.
